# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: application-demo-config
#   namespace: default
# data:
#   NEW_FEATURE: "true"

# ---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: application-demo
  namespace: default
  labels:
    stack: frontend
    app: application
spec:
  replicas: 5
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: primary
        image: gcr.io/autingo-159109/rnr-app
        ports:
        - containerPort: 3000
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 3000
        # envFrom:
        # - configMapRef:
        #     name: application-demo-config

---

kind: Service
apiVersion: v1
metadata:
  name: application-demo
  namespace: default
spec:
  selector:
    app: application
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000